### ISSUE TITLE
lookup value for match / debug value

### ISSUE THREAD

**Issue by unusualevent** [ansible-collections/community.dns#129]
##### SUMMARY
It would be useful to see how dnspython's interpretation of a DNS record does or doesn't match (e.g., quoting) - to know why the record isn't matched.

exposing the current value as part of a failed output would be great.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.dns.wait_for_txt

##### ADDITIONAL INFORMATION
debugging what the ansible resolver config's lookup received would be useful...

```yaml
- name: Wait for terraform changes
  community.dns.wait_for_txt:
    records:
      - name: example.com
        values: var.expected_value
        mode: equals
```

similar to printing failed lookups, this'd print unequal lookups. or at least register them to an output / error.

maybe registering a DNS output via this module is a better feature request...
