### ISSUE TITLE
Recursively get responsible nameservers (nearest responsible nameserver)

### ISSUE THREAD

**Issue by hakong** [ansible-collections/community.dns#170]
##### SUMMARY

A parameter that would enable getting nameservers of the nearest zone, if the record being queried does not exist.
For example: getting the nameservers responsible for `foo.bar.example.org` where `foo` or even `foo.bar` don't exist. In that case the module would recursively look up nameservers until it finds the nearest responsible NS.

~~~
[root@manage ~]# dig NS foo.bar.example.org +short
[root@manage ~]# dig NS bar.example.org +short
[root@manage ~]# dig NS example.org +short
a.iana-servers.net.
b.iana-servers.net.
~~~
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nameserver_info

##### ADDITIONAL INFORMATION

My current usecase is creating TXT records for authenticating a domain/subzone where the domain/subzone does not exist on the DNS server (the domain exists, just not the subzone/subdomain).

My ansible playbook needs to know where to create the DNS records (what provider/server). I just specify a list of SANs I would like in the certificate and it creates all the necessary DNS records for authenticating, regardless of hosting provider/server and wether the records/zones have been created or not.

**Example behavior now:**
```yaml
  tasks:
    - name: Find responsible nameservers
      community.dns.nameserver_info:
        name:
          - example.org
          - bar.example.org
          - foo.bar.example.org
      register: result
      failed_when: false

    - name: Show nameservers
      ansible.builtin.debug:
        msg: '{{ result }}'
```
Result:
```
ok: [localhost] => {
    "msg": {
        "changed": false,
        "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py\", line 297, in guarded_run\n    return runner()\n           ^^^^^^^^\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/modules/nameserver_info.py\", line 172, in f\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py\", line 245, in resolve_nameservers\n    nameservers = self._lookup_ns(dnsname)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py\", line 219, in _lookup_ns\n    result = self._do_lookup_ns(target)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py\", line 204, in _do_lookup_ns\n    nameserver_names, cname = self._lookup_ns_names(target_part, nameservers=nameservers, nameserver_ips=nameserver_ips)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py\", line 164, in _lookup_ns_names\n    self._handle_reponse_errors(target, response, nameserver=nameserver_ips[0], query='get NS for \"%s\"' % target)\n  File \"/tmp/ansible_community.dns.nameserver_info_payload_hakak0ng/ansible_community.dns.nameserver_info_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py\", line 49, in _handle_reponse_errors\n    raise dns.resolver.NXDOMAIN(qnames=[target], responses={target: response})\ndns.resolver.NXDOMAIN: The DNS query name does not exist: bar.example.org.\n",
        "failed": false,
        "failed_when_result": false,
        "msg": "Unexpected DNS error: The DNS query name does not exist: bar.example.org.",
        "results": [
            {
                "name": "example.org",
                "nameservers": [
                    "a.iana-servers.net.",
                    "b.iana-servers.net."
                ]
            },
            {
                "name": "bar.example.org"
            },
            {
                "name": "foo.bar.example.org"
            }
        ]
    }
}
```

**Example behavior with recursive_lookup: true (parameter name could be something else)**
```
  tasks:
    - name: Find responsible nameservers
      community.dns.nameserver_info:
        name:
          - example.org
          - bar.example.org
          - foo.bar.example.org
        recursive_lookup: true
      register: result
      failed_when: false

    - name: Show nameservers
      ansible.builtin.debug:
        msg: '{{ result }}'
```
Result:
```
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "failed_when_result": false,
        "results": [
            {
                "name": "example.org",
                "nameservers": [
                    "a.iana-servers.net.",
                    "b.iana-servers.net."
                ]
            },
            {
                "name": "bar.example.org",
                "nameservers": [
                    "a.iana-servers.net.",
                    "b.iana-servers.net."
                ]
            },
            {
                "name": "foo.bar.example.org",
                "nameservers": [
                    "a.iana-servers.net.",
                    "b.iana-servers.net."
                ]
            }
        ]
    }
}
```
