### ISSUE TITLE
community.dns.hetzner_dns_record_info returning empty list

### ISSUE THREAD

**Issue by PeterSchumacher** [ansible-collections/community.dns#184]
##### SUMMARY
The Hetzner DNS record info module is not returning any records

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.dns.hetzner_dns_record_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/peter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/peter/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/peter/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/peter/.local/bin/ansible
  python version = 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] (/home/peter/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/peter/.ansible/collections/ansible_collections
Collection    Version
------------- -------
community.dns 2.8.0  

# /home/peter/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection    Version
------------- -------
community.dns 2.8.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
EDITOR(env: EDITOR) = micro
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Ubuntu MATE 23.10 with ansible installed via pipx

##### STEPS TO REPRODUCE

```yaml
---
- name: Hetzner DNS
  hosts: all
  gather_facts: false
  vars:
    hetzner_auth_api_token: "{{ lookup('env','HETZNER_AUTH_API_TOKEN') }}"

  tasks:
    - name: Hent information om et DNS-recordsæt
      community.dns.hetzner_dns_record_info:
        zone: schumacher.dk
        record: "gaston.schumacher.dk"
        type: A
        hetzner_token: "{{ hetzner_auth_api_token }}"
      register: rec

    - name: Udskriv information om DNS-recordsættet
      ansible.builtin.debug:
        var: rec.records
```

##### EXPECTED RESULTS

A list of DNS records

##### ACTUAL RESULTS

```paste below
ok: [server-01.dockerhost.dk] => {
    "rec.records": []
}
```
