### ISSUE TITLE
txt_transformation doesn't work with Hetzner API

### ISSUE THREAD

**Issue by chuegel** [ansible-collections/community.dns#190]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
<!--- Explain the problem briefly below -->
When using `txt_transformation: quoted` the TXT record cannot be pushed to the Hetzner API

```
- name: "Update DNS TXT record"                                                                                       
  community.dns.hetzner_dns_record:
    state: present                                                                                                                                                                                                                           
    zone: example.tech                                                                                                                                                                                                                 
    record: text.example.tech                                                                       
    type: TXT                                                                                                                                                                                                                                
    txt_transformation: quoted
    ttl: 7200          
    value: "{{ lookup('file', '{{ playbook_dir }}/../templates/text.json') }}"                                                                                                                                                           
    hetzner_token: "{{ lookup('ansible.builtin.env', 'HETZNER_TOKEN') }}"                                             
```


##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
 txt_transformation
##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
ansible [core 2.14.3]
```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
Collection    Version
------------- -------
community.dns 2.8.1 
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
ANSIBLE_NOCOWS(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = True
CALLBACKS_ENABLED(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = ['timer']
COLLECTIONS_PATHS(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = ['/home/user/Documents/gitlab/ansible-network-automation/collections']
CONFIG_FILE() = /home/user/Documents/gitlab/ansible-network-automation/ansible.cfg
DEFAULT_GATHERING(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = explicit
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = ['/home/user/Documents/gitlab/ansible-network-automation/roles']
DEFAULT_STDOUT_CALLBACK(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = True
HOST_KEY_CHECKING(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = /usr/bin/python3
INVENTORY_ENABLED(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'netbox.netbox.nb_inventory']
PERSISTENT_COMMAND_TIMEOUT(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = 180
SYSTEM_WARNINGS(/home/user/Documents/gitlab/ansible-network-automation/ansible.cfg) = True
```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
Ubuntu 22.04

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
Works:
```yaml
- name: "Update DNS TXT record"                                                                                       
  community.dns.hetzner_dns_record:
    state: present                                                                                                                                                                                                                           
    zone: example.tech                                                                                                                                                                                                                 
    record: text.example.tech                                                                       
    type: TXT                                                                                                                                                                                                                                
    ttl: 7200          
    value: "{{ lookup('file', '{{ playbook_dir }}/../templates/text.json') }}"                                                                                                                                                           
    hetzner_token: "{{ lookup('ansible.builtin.env', 'HETZNER_TOKEN') }}"      
```
Doesn't work:

```yaml
- name: "Update DNS TXT record"                                                                                       
  community.dns.hetzner_dns_record:
    state: present                                                                                                                                                                                                                           
    zone: example.tech                                                                                                                                                                                                                 
    record: text.example.tech                                                                       
    type: TXT                                                                                                                                                                                                                                
    txt_transformation: quoted
    ttl: 7200          
    value: "{{ lookup('file', '{{ playbook_dir }}/../templates/text.json') }}"                                                                                                                                                           
    hetzner_token: "{{ lookup('ansible.builtin.env', 'HETZNER_TOKEN') }}"      
```

```bash
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.dns.plugins.module_utils.zone_record_api.DNSAPIError: Expected HTTP status 200, 422 for POST https://dns.hetzner.com/api/v1/records, but got HTTP status 502 (Unknown Error) with message "An invalid response was received from the upstream server"
fatal: [localhost]: FAILED! => changed=false 
  error: Expected HTTP status 200, 422 for POST https://dns.hetzner.com/api/v1/records, but got HTTP status 502 (Unknown Error) with message "An invalid response was received from the upstream server"
  msg: 'Error: Expected HTTP status 200, 422 for POST https://dns.hetzner.com/api/v1/records, but got HTTP status 502 (Unknown Error) with message "An invalid response was received from the upstream server"'
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->


##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
see above
<!--- Paste verbatim command output between quotes -->
```paste below

```
