### ISSUE TITLE
MX Record using community.dns.hetzner_dns_record:

### ISSUE THREAD

**Issue by f0r3n51c6uy** [ansible-collections/community.dns#232]
I tried to create a MX record using `community.dns.hetzner_dns_record` but didn't succeed. The documentation doesn't explain how to provide the `priority` information. I tried the following 

```ansible
 community.dns.hetzner_dns_record:
    hetzner_token: "{{ hetzner_dns_api_token }}"
    zone_name: test.local
    type: MX
    value: mx.test.local
    priority: 0
    state: present
```
Since the `priority` keyword isn't defined it obviously fails. What is the correct way to add a MX record using `community.dns.hetzner_dns_record` ?

**Comment by felixfontein** [comment]
The format of MX entries is `<priority> <host>`, so you'd set `value` to `0 mx.test.local` in your example:
```yaml
 community.dns.hetzner_dns_record:
    hetzner_token: "{{ hetzner_dns_api_token }}"
    zone_name: test.local
    type: MX
    value: 0 mx.test.local
    state: present
```
