### ISSUE TITLE
community.dns.wait_for_txt doesn't seem to actually wait for a **new** record.

### ISSUE THREAD

**Issue by zoredache** [ansible-collections/community.dns#81]
##### SUMMARY
Using ansible to get letcencrypt cert, and using wait_for_txt, to wait for the DNS challenges to be published to get replicated to all authoritative, module fails, if the record doesn't exist yet.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
wait_for_txt

##### ANSIBLE VERSION

```paste below

    # ansible --version
    ansible [core 2.12.1]
      config file = ./ansible.cfg
      configured module search path = [...]
      ansible python module location = /usr/local/ansible/stable/lib/python3.9/site-packages/ansible
      ansible collection location = ...
      executable location = /usr/local/bin/ansible
      python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
      jinja version = 3.0.1
      libyaml = True

```

##### COLLECTION VERSION

```paste below

ansible-galaxy collection list community.dns

    # /home/cfrancy/Projects/nwesd_ansible/.ansible/collections/ansible_collections
    Collection    Version
    ------------- -------
    community.dns 2.0.4  
```

##### EXPECTED RESULTS

I don't expect wait_for_txt to fail, when the record doesn't exist yet, I expect it to **wait** for the txt record to exist.

##### STEPS TO REPRODUCE

```yaml

    - name: Wait for DNS records
      delegate_to: "{{ authoritative_dns_server }}"
      when: acme_data is changed
      delay: 30
      retries: 30
      tags:
      - verify_dns
      community.dns.wait_for_txt:
        timeout: 3600
        max_sleep: 60
        records: >-
          [
          {% for item in query('dict', acme_data.challenge_data_dns) %}
          {% for value in item.value %}
          {
            "mode": "subset",
            "name": "{{ item.key }}",
            "values": "{{ value }}"
          },
          {% endfor %}
          {% endfor %}
          ]

```

##### ACTUAL RESULTS

```paste below

    TASK [Wait for DNS records] ***************************************************************************************************************
    ...
    <dns-01.example..org> (0, b'', b'')
    The full traceback is:
      File "/tmp/ansible_community.dns.wait_for_txt_payload_30h2d7y5/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/modules/wait_for_txt.py", line 273, in main
      File "/tmp/ansible_community.dns.wait_for_txt_payload_30h2d7y5/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/modules/wait_for_txt.py", line 194, in lookup
      File "/tmp/ansible_community.dns.wait_for_txt_payload_30h2d7y5/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py", line 176, in resolve
        response = self._handle_timeout(resolver.resolve, dnsname, lifetime=self.timeout, **kwargs)
      File "/tmp/ansible_community.dns.wait_for_txt_payload_30h2d7y5/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py", line 54, in _handle_timeout
        return function(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1030, in resolve
        (request, answer) = resolution.next_request()
      File "/usr/lib/python3/dist-packages/dns/resolver.py", line 584, in next_request
        raise NXDOMAIN(qnames=self.qnames_to_try,
    fatal: [docker-01.example.org -> dns-01.example..org]: FAILED! => {
        "changed": false,
        "completed": 0,
        "invocation": {
            "module_args": {
                "always_ask_default_resolver": true,
                "max_sleep": 60.0,
                "query_retry": 3,
                "query_timeout": 10.0,
                "records": [
                    {
                        "mode": "subset",
                        "name": "_acme-challenge.www.site.example.org",
                        "values": [
                            "1RvkyK_9ZES_huVdLbUqFnD1wPzQiUJWw8avhbUmc3M"
                        ]
                    },
                    {
                        "mode": "subset",
                        "name": "_acme-challenge.site.example.org",
                        "values": [
                            "EjE8ptD2SM-rBJzhaEpfeSXJ2hnEOjSH_NXsDQmmW5A"
                        ]
                    }
                ],
                "timeout": 3600.0
            }
        },
        "msg": "Unexpected DNS error: The DNS query name does not exist: _acme-challenge.www.site.example.org.",
        "records": [
            {
                "check_count": 0,
                "done": false,
                "name": "_acme-challenge.www.site.example.org"
            },
            {
                "check_count": 0,
                "done": false,
                "name": "_acme-challenge.site.example.org"
            }
        ]
    }
```
